language: go

go:
  - 1.8
  - tip

services:
  - postgresql

before_install:
  - psql -c 'create database crud_api;' -U postgres

install:
  - go get .
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=coverage.out
