language: go

go:
  - 1.9
  - tip

services:
  - postgresql

before_install:
  - psql -c 'create database crud_api;' -U postgres

install:
  - go get ./...
  - go get github.com/mattn/goveralls

script:
  - DBTYPE=postgres go test -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
