language: go

go:
  - 1.8
  - tip

services:
  - postgresql

before_install:
  - psql -c 'create database crud_api;' -U postgres

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/gorilla/mux
  - go get github.com/go-sql-driver/mysql

script:
  - go test -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
